# Generated by Django 5.1.1 on 2024-10-01 18:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailored_feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question', models.JSONField()),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('feedback_image', models.ImageField(blank=True, null=True, upload_to='feedback_images/')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_assessment', to='tailored_feed.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=80)),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('in_process', 'In Process'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_assessment', to='tailored_feed.assessment')),
            ],
            options={
                'ordering': ['creationDate'],
                'unique_together': {('assessment', 'creationDate')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_student', to=settings.AUTH_USER_MODEL)),
                ('assessmentSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tailored_feed.assessmentsession')),
            ],
        ),
    ]
