# Generated by Django 5.1.1 on 2024-10-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailored_feed', '0002_assessment_assessmentquestion_assessmentsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
